#!/usr/bin/env bash

# entry script to launch PaperPi

PROGRAM_PATH=/usr/local/paperpi
VENV_PATH="$PROGRAM_PATH/venv_paperpi"

source "$VENV_PATH/bin/activate"

$(realpath $PROGRAM_PATH/paperpi.py "$@")

deactivate


